name: Build python package wheel and tarball

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Python wheel and upload artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist
        .
    - name: Publish dist
      uses: actions/upload-artifact@v2
      with:
        name: PyHardwareMonitor
        path: |
          dist
